template: array_iops_drop
on: disk_ops
lookup: ops
units: ops/s
every: 3600s
warn: sum($this) < (avar(5m, sum($this)) * 0.7)
crit: sum($this) < (avar(5m, sum($this)) * 0.5)
info: "Array IOPS drop detected"
-to: sysadmin
rearm: 10m