template: hdd_latency_increase
on: system.io
lookup: disk_write_latency
units: ms
every: 21600s        # hourly, matches HDD smartctl
warn: $this > 25
crit: $this > 50
info: "Disk write latency increased"
-to: sysadmin
rearm: 14400s