template: mem_usage
on: system.ram
lookup: used
units: %
every: 60s
warn: $this > 80
crit: $this > 95
info: "Memory usage high"
-to: sysadmin
rearm: 2m

template: swap_usage
on: system.swap
lookup: used
units: %
every: 60s
warn: $this > 10
crit: $this > 20
info: "Swap usage high"
-to: sysadmin
rearm: 5m