local:
  devices:
    - "/dev/disk/by-id/ata-*"       # All SATA HDDs/SSDs
    - "/dev/disk/by-id/nvme-*"      # All NVMe drives
  update_every: 21600               # 6 hourly polling for HDDs; SSD/NVMe ignored here are fast