template: array_hdd_smart
on: smartctl
lookup: reallocated_sectors_count
units: sectors
every: 3600s
warn: sum($this) > 0
crit: sum($this) > 20
info: "Aggregated HDD reallocated sectors in array"
-to: sysadmin
rearm: 2h