template: btrfs_scrub_errors
on: btrfs.scrub
lookup: errors
units: errors
every: 300s         # matches BTRFS plugin
warn: $this > 0
crit: $this > 5
info: "BTRFS scrub reported errors"
-to: sysadmin
rearm: 1h