template: disk_iops_drop
on: disk_ops
lookup: ops
units: ops/s
every: 3600s
warn: $this < (avar(5m,$this)*0.7)
crit: $this < (avar(5m,$this)*0.5)
info: "Disk IOPS drop detected"
-to: sysadmin
rearm: 10m