template: docker_io
on: docker.io
lookup: write_ops
units: ops/s
every: 60s
warn: $this < (avar(5m,$this)*0.7)
crit: $this < (avar(5m,$this)*0.5)
info: "Docker container I/O drop"
-to: sysadmin
rearm: 10m