template: net_err_out
on: net
lookup: errors_out
units: packets
every: 60s
warn: $this > 0
crit: $this > 5
info: "Network interface sending errors"
-to: sysadmin
rearm: 5m

template: net_err_in
on: net
lookup: errors_in
units: packets
every: 60s
warn: $this > 0
crit: $this > 5
info: "Network interface receiving errors"
-to: sysadmin
rearm: 5m

template: net_throughput_drop
on: net.bytes
lookup: out
units: bytes/s
every: 60s
warn: $this < (avar(5m,$this)*0.5)
crit: $this < (avar(5m,$this)*0.3)
info: "Network throughput drop"
-to: sysadmin
rearm: 10m