template: psu_voltage
on: sensors.voltage
lookup: voltage
units: V
every: 60s
warn: $this < 11.5 or $this > 12.5
crit: $this < 11 or $this > 13
info: "PSU voltage out of range"
-to: sysadmin
rearm: 10m